### ISSUE TITLE
Sometimes "Displaying schedule" counter shows negative numbers in the nominator

### ISSUE THREAD

**Issue by dimonoid** [morinted/schedule-generator#41] opened 2019-06-04 18:09 UTC
I didn't understand exactly when it happens, but it is definitely a bug. Once reached negatives, one can still safely click next and last buttons to navigate, but the schedule is shown as empty.

**Comment by davidschlachter** [comment] 2019-06-04 19:06
Thanks for the report! If you're able to reproduce the issue with a particular set of courses or steps, please add a comment so we can look into this further.

**Comment by davidschlachter** [comment] 2020-05-21 13:13
Closing issue - unable to reproduce.

**Closed by davidschlachter** 2020-05-21 13:13 UTC
Labels: bug
